pipeline:
  name: ravi-harness-go-pipeline-sample
  identifier: Build_ravimtestgit_harness_go_pipeline_sample_1723414891425
  projectIdentifier: raviexercise
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Run Unit Tests
                  identifier: Echo_Welcome_Message
                  spec:
                    connectorRef: account.DockerHubAccess
                    image: golang:1.15
                    shell: Sh
                    command: |-
                      set *e
                      go get gotest.tools/gotestsum
                      gotestsum --format=standard-verbose --junitfile unit-tests.xml
                      exit
              - step:
                  type: Run
                  name: Build Application
                  identifier: Build_Application
                  spec:
                    connectorRef: account.DockerHubAccess
                    image: golang:1.15
                    shell: Sh
                    command: |-
                      set *e
                      goget gotest.tools/gotestsum
                      CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -tags netgo
                      exit 0
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_Go
                  identifier: BuildAndPushDockerRegistry_Go
                  spec:
                    connectorRef: account.DockerHubAccess
                    repo: rmettadocker/harnessexercise
                    tags:
                      - latestGo
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
    - stage:
        name: Deployment
        identifier: Deployment
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: raviservice
            serviceInputs:
              serviceDefinition:
                type: Kubernetes
                spec:
                  artifacts:
                    primary:
                      primaryArtifactRef: <+input>
                      sources: <+input>
          environment:
            environmentRef: testingenvironment
            deployToAll: false
            infrastructureDefinitions:
              - identifier: harnessk8sinfradef
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1723388863815
        repoName: ravimtestgit/harness-go-pipeline-sample
        build: <+input>
